
market:
  listpair: ETH_BTC;GTO_BTC;TRX_BTC

depthprice:
  wss:
    host: 0.0.0.0
    port: 15501

historytrade:
  wss:
    host: 0.0.0.0
    port: 15701

candlesticks:
  wss:
    host: 0.0.0.0
    port: 15601

ticker24h:
  wss:
    host: 0.0.0.0
    port: 15801

webserver:
  host: 0.0.0.0
  port: 15901

dataws:
  host: 127.0.0.1
  port: 15401
